### ISSUE TITLE
readable items debug

### ISSUE THREAD

**Issue by Seliro** [babymannen/theforgottenserver-7.4#1]
`
+---------------------------------------------------------------
Debug Assertion 7.72 Control.cpp 1274
Fri Aug 19 20:17:38 2016
Windows Version: 6.1 build 7601 on 2 with Service Pack 1
Graphic Engine: 1
Last Packet Types: 000 150 101 109 030 101 109 103 109 103
Last Packet: 118 012 150 001 000 000 000 127 008 103 012 103 012 083 112 101
Player Position: [990,1016,7]
Player.cpp 383: exception occurred, reason:
Network.cpp 885: exception occurred (ErrorCode = 0), reason:
Control.cpp 1280: exception occurred (Type = 0), reason:
Control.cpp 1274: unknown packet type during game (Type = 0)
----------------------------------------------------------------`

**Comment by babymannen** [comment]
Commited fix to this error.
