### ISSUE TITLE
Players can block ranged attack from monsters.

### ISSUE THREAD

**Issue by peonso** [babymannen/theforgottenserver-7.4#12]
https://otland.net/threads/distance-attacks-are-blocked-by-shield.238082/

https://github.com/babymannen/theforgottenserver-7.4/blob/master/src/monsters.cpp#L400

		if ((attr = node.attribute("checkshield"))) {
		   combat->setParam(COMBAT_PARAM_BLOCKSHIELD, 1);
		}

**Comment by babymannen** [comment]
Fixed. Thanks.
