### ISSUE TITLE
Monsters summon as defensive behavior

### ISSUE THREAD

**Issue by peonso** [babymannen/theforgottenserver-7.4#13]
https://github.com/otland/forgottenserver/pull/685#issuecomment-39106747

https://github.com/babymannen/theforgottenserver-7.4/blob/master/src/monster.cpp#L935

	if (attackedCreature && !isSummon() && summons.size() < mType->maxSummons) {

**Comment by Seliro** [comment]
this was added in 7925ee31e38e3c15e729292372ff87c40e11b353
