### ISSUE TITLE
Ranged monsters should properly pick the nearest player as target when changing target

### ISSUE THREAD

**Issue by peonso** [babymannen/theforgottenserver-7.4#18]
Ranged monsters should properly pick the nearest player as target when changing target (even if it's the same player).

https://github.com/babymannen/theforgottenserver-7.4/blob/master/src/monster.cpp#L494

	bool Monster::searchTarget(TargetSearchType_t searchType /*= TARGETSEARCH_DEFAULT*/)
	{
		std::list<Creature*> resultList;
		const Position& myPos = getPosition();

		for (Creature* creature : targetList) {
			if (followCreature != creature && isTarget(creature)) {
				if (searchType == TARGETSEARCH_RANDOM || canUseAttack(myPos, creature)) {
					resultList.push_back(creature);
				}
			}
		}

		switch (searchType) {
			case TARGETSEARCH_NEAREST: {
				Creature* target = nullptr;
				if (!targetList.empty()) {
					auto it = targetList.begin();
					target = *it;

					if (++it != targetList.end()) {
						const Position& targetPosition = target->getPosition();
						int32_t minRange = Position::getDistanceX(myPos, targetPosition) + Position::getDistanceY(myPos, targetPosition);
						do {
							const Position& pos = (*it)->getPosition();

							int32_t distance = Position::getDistanceX(myPos, pos) + Position::getDistanceY(myPos, pos);
							if (distance < minRange) {
								target = *it;
								minRange = distance;
							}
						} while (++it != targetList.end());
					}
				} else {
					int32_t minRange = std::numeric_limits<int32_t>::max();
					for (Creature* creature : targetList) {

						const Position& pos = creature->getPosition();
						int32_t distance = Position::getDistanceX(myPos, pos) + Position::getDistanceY(myPos, pos);
						if (distance < minRange) {
							target = creature;
							minRange = distance;
						}
					}
				}

				if (target && selectTarget(target)) {
					return true;
				}
				break;
			}

			case TARGETSEARCH_DEFAULT:
			case TARGETSEARCH_ATTACKRANGE:
			case TARGETSEARCH_RANDOM:
			default: {
				if (!resultList.empty()) {
					auto it = resultList.begin();
					std::advance(it, uniform_random(0, resultList.size() - 1));
					return selectTarget(*it);
				}

				if (searchType == TARGETSEARCH_ATTACKRANGE) {
					return false;
				}

				break;
			}
		}

		//lets just pick the first target in the list
		for (Creature* target : targetList) {
			if (followCreature != target && selectTarget(target)) {
				return true;
			}
		}
		return false;
	}

**Comment by babymannen** [comment]
Thanks

**Comment by Seliro** [comment]
@peonso, does this work good?,
https://github.com/peonso/tibialegacyserver/commit/ce23068d5cc3014641deb6fb3c7023eba30ced97
https://github.com/peonso/tibialegacyserver/commit/5fb2ed14e9494c57dd925fc256912e3b20be3704

if so maby it could get implemented?

**Comment by peonso** [comment]
@babymannen working on this right now
