### ISSUE TITLE
chat channels debug

### ISSUE THREAD

**Issue by Seliro** [babymannen/theforgottenserver-7.4#2]
`+---------------------------------------------------------------
Debug Assertion 7.72 Utils.cpp 340
Fri Aug 19 21:02:35 2016
Windows Version: 6.1 build 7601 on 2 with Service Pack 1
Graphic Engine: 1
Last Packet Types: 170 160 160 172 171 030 160 160 104 109
Last Packet: 023 000 170 001 000 000 000 006 000 083 101 108 105 114 111 001
Player Position: [996,1009,7]
Player.cpp 383: exception occurred, reason:
Network.cpp 885: exception occurred (ErrorCode = 0), reason:
Control.cpp 1280: exception occurred (Type = 170), reason:
Communication.cpp 2466: exception occurred (Mode = 1) (Channel = 0), reason:
Network.cpp 470: exception occurred (MaxLength = 512), reason:
Utils.cpp 340: assertion failed (Position = 25) (Size-Length = -27621), reason:
Position<=Size-Length
----------------------------------------------------------------`

**Comment by babymannen** [comment]
Commited fix to this error.
