### ISSUE TITLE
config options to features and issues

### ISSUE THREAD

**Issue by Seliro** [babymannen/theforgottenserver-7.4#23]
> **Features** that wants a config option
----------------------
* monster idle (something similar that othire had)
```
--how many floors away of a player should a monster be to become idle?
--WARNING: setting this as any number bigger than 3 may increase CPU usage and
--setting this to any value smaller than 2 will make nearly impossible to rope monsters from a hole
height_minimum_for_idle = 2
```
* promotion and price (not tested)
* blessings and price (not tested)
* party shared experience (not tested)
* rook system?
* skull system?
* bank system?
* rateGold
* decimal rates
* be able to multiply rune charges
* loot message
* anti magebomb system

> **Misc**
----------------------
* tibia cam?
* floor save/resets (not tested)
* raids (not tested)
* light aura around monster, if demon loot is fire axe, then the demon have a red aura around it for example until it dies ofc

> **Issues** that wants a config option
----------------------
(https://github.com/babymannen/theforgottenserver-7.4/issues/28) fields block ladders (they already do)
(https://github.com/babymannen/theforgottenserver-7.4/issues/38) summons and experience
(https://github.com/babymannen/theforgottenserver-7.4/issues/41) conjure runes in backpack

* soul system (not tested, but it should not exist in 7.4, and we actually use a 7.72 client)
* items or fields blocking rope spot (they currently don't)

il update if i can think of something more

**Comment by peonso** [comment]
fields blocked ladders? =0

**Comment by peonso** [comment]
break this down in a series of issues, better to others too keep track of everything/address an specific one.

**Comment by Seliro** [comment]
ok

**Comment by bangbus** [comment]
I've added these in config so far. More to come. Right now I'm trying to solve #46 

`showLootMessage = true
checkCorpseOwner = false
antiHouseTrash = true
animateHealthChange = false
spectatorMessage = false`

Spectator messages are the damage/heal messages that pop up for people around a player, like "Bob lost 47 hitpoints due to an attack by a demon", "Bob healed for 45 hitpoints"

I will try and commit when I come home, don't know how it works but I will try!

**Comment by Seliro** [comment]
can you post your lootmessage fix?

**Comment by babymannen** [comment]
Come back with one and one at the time please
