### ISSUE TITLE
rope creatures

### ISSUE THREAD

**Issue by Seliro** [babymannen/theforgottenserver-7.4#29]
you cannot rope creatures from sewers and rope spots atm

![1](http://i.imgur.com/8GhP06j.png)
![2](http://i.imgur.com/DhlO9de.png)

add option for it

**Comment by peonso** [comment]
try this. https://github.com/babymannen/theforgottenserver-7.4/blob/master/server/data/actions/scripts/tools/rope.lua

	local holeId = {
		294, 369, 370, 383, 392, 408, 409, 410, 427, 428, 430, 462, 469, 470, 482,
		484, 485, 489, 924, 3135, 3136
	}

	function onUse(player, item, fromPosition, target, toPosition)
		local tile = Tile(toPosition)
		if not tile then
			return false
		end

		if isInArray(ropeSpots, tile:getGround():getId()) then
			player:teleportTo(toPosition:moveUpstairs(), false)
			return true
		elseif isInArray(holeId, target.itemid) then
			toPosition.z = toPosition.z + 1
			tile = Tile(toPosition)
			if tile then
				local thing = tile:getTopVisibleThing()
				if thing:isItem() and thing:getType():isMovable() then
					return thing:moveTo(toPosition:moveUpstairs())
				elseif thing:isCreature() then
					return thing:teleportTo(toPosition:moveUpstairs())
				end
			end
			player:sendCancelMessage(RETURNVALUE_NOTPOSSIBLE)
			return true
		end
		return false
	end

**Comment by Seliro** [comment]
works

**Comment by peonso** [comment]
https://github.com/babymannen/theforgottenserver-7.4/commit/42d66b4061dbf432ab05e455c95b5af9a1cf211a
