### ISSUE TITLE
player death debug

### ISSUE THREAD

**Issue by Seliro** [babymannen/theforgottenserver-7.4#3]
`
+---------------------------------------------------------------
Debug Assertion 7.72 Control.cpp 1274
Fri Aug 19 23:41:31 2016
Windows Version: 6.1 build 7601 on 2 with Service Pack 1
Graphic Engine: 2
Last Packet Types: 040 161 160 180 160 120 160 141 121 160
Last Packet: 223 000 108 213 048 225 048 007 001 106 213 048 225 048 007 070
Player Position: [12501,12513,7]
Player.cpp 383: exception occurred, reason:
Network.cpp 885: exception occurred (ErrorCode = 0), reason:
Control.cpp 1280: exception occurred (Type = 40), reason:
Control.cpp 1274: unknown packet type during game (Type = 40)
----------------------------------------------------------------`

**Comment by babymannen** [comment]
Commited fix to this error.
