### ISSUE TITLE
player stack and damage

### ISSUE THREAD

**Issue by Seliro** [babymannen/theforgottenserver-7.4#30]
Tested the same thing **Biskuait** did in the video with sudden death rune on the same stack at the other player and i noticed that it is currently reversed on this repo.

I only tested with 2 players tho, but i assume if there is more players on the stack they should also take damage, maby someone can confirm that

https://www.youtube.com/watch?v=F3f8MU63ZGk&feature=youtu.be&t=12m55s

Already talked to @babymannen about it, just a reminder.

**Comment by babymannen** [comment]
I guess you mean that the stack is reversed? At least visibly? Does it really matter? >_<

**Comment by babymannen** [comment]
I have no idea what you're talking about
