### ISSUE TITLE
logout and protection zone

### ISSUE THREAD

**Issue by Seliro** [babymannen/theforgottenserver-7.4#34]
Characters can currently always log out in a protection zone regardless of whether or not the logout block is active.

**Comment by bangbus** [comment]
Very simple fix, in protocolgame.cpp > `ProtocolGame::logout` change:

`if (!player->getTile()->hasFlag(TILESTATE_PROTECTIONZONE) && player->hasCondition(CONDITION_INFIGHT)) {`

to

`if (player->hasCondition(CONDITION_INFIGHT)) {`

**Comment by Seliro** [comment]
thank you
