### ISSUE TITLE
npc walking issue

### ISSUE THREAD

**Issue by Seliro** [babymannen/theforgottenserver-7.4#36]
they should not be able to walk upon crates, boxes etc
https://youtu.be/1T6PCZu25eQ?t=4m25s

currently they do
![npcwalk](http://i.imgur.com/eyCuPqQ.png)

**Comment by peonso** [comment]
`ignoreheight="0"` to NPC file might solve it. Like this 

    <?xml version="1.0" encoding="UTF-8"?>
    <npc name="Guide Benedict" script="Guide Benedict.lua" walkinterval="2000" speed="100" walkradius="4" floorchange="0" ignoreheight="0">
    	<health max="100" now="100"/>
    	<look type="57"/>
    </npc>

**Comment by Seliro** [comment]
yeah, you are correct! :)
