### ISSUE TITLE
spells and random tile damage

### ISSUE THREAD

**Issue by Seliro** [babymannen/theforgottenserver-7.4#37]
# should have random tile damage
- [ ] ultimate explosion (http://s22.photobucket.com/user/Paker/media/Test%20Hits/BestUe.jpg.html)
- [ ] berserk (i lost the image lol, il find it later)
- [ ] explosion rune (http://s22.photobucket.com/user/Paker/media/Test%20Hits/Explopakerjpg.jpg.html)

# should not have random tile damage
- [ ] great fireball rune (http://s22.photobucket.com/user/Paker/media/Test%20Hits/Gfbjpg.jpg.html)
- [ ] energy wave (http://s22.photobucket.com/user/Paker/media/Test%20Hits/Ew181jpg.jpg.html)
- [ ] great energy beam (http://s22.photobucket.com/user/Paker/media/Test%20Hits/vislux166jpg.jpg.html)

I dont knw all the spells but here is some that i found with some pictures aswell.

**Comment by Seliro** [comment]
maby have a new attribute in spells that says randomdamage="1"  or something

**Comment by peonso** [comment]
It's not about random damage, its about armor reduction for physical spells. As it creature/player rolls armor separately they will take different damage from physical spells.

**Comment by Seliro** [comment]
its not just physical spells

**Comment by peonso** [comment]
You listed 3 physical spells them listed 3 "elemental" ones.

**Comment by Seliro** [comment]
i noticed now, yeah it makes sense, thx im tired ;D
