### ISSUE TITLE
summons and experience

### ISSUE THREAD

**Issue by Seliro** [babymannen/theforgottenserver-7.4#38]
i cant remember if they got exp in 7.4, but they currently do now anywy
![exp](http://i.imgur.com/36HkPvZ.png)

**Comment by peonso** [comment]
They did, but I think the ammount of exp might be wrong.

![exp](http://i.imgur.com/XiLbn1B.gif)

**Comment by peonso** [comment]
I don't know if you have it, but there are tons of videos for Tibia Time Machine here: http://www.4shared.com/folder/SQugRKq1/Tibia_Time_Machine.html

You can get TTM here:
https://otland.net/threads/tibia-time-machine-5-8.222290/

**Comment by babymannen** [comment]
They did get exp back then (you get 50% and the summon or summon get 50% (or share 50% if more than one). I won't be filling the server with config options for everything.
