### ISSUE TITLE
outfits debug

### ISSUE THREAD

**Issue by Seliro** [babymannen/theforgottenserver-7.4#4]
when switching outfit and it lands on either looktype 135 (male) or 143 (female), client debugs

`+---------------------------------------------------------------
Debug Assertion 7.72 Objects.cpp 241
Sat Aug 20 00:44:52 2016
Windows Version: 6.1 build 7601 on 2 with Service Pack 1
Graphic Engine: 2
Last Packet Types: 030 200 160 180 180 162 141 130 161 160
Last Packet: 001 000 030 051 051 051 051 051 000 000 000 000 000 000 000 000
Player Position: [12497,12503,7]
Player.cpp 383: exception occurred, reason:
Player.cpp 456: exception occurred, reason:
Control.cpp 1560: exception occurred (Type = 0), reason:
Control.cpp 366: exception occurred (Force?1:0 = 0), reason:
GUI.cpp 1408: exception occurred (Surface = 1), reason:
GUI.cpp 1408: exception occurred (Surface = 1), reason:
GUI.cpp 1408: exception occurred (Surface = 1), reason:
DialogElements.cpp 911: exception occurred (Surface = 1), reason:
graphics.cpp 1137: exception occurred (Surface = 1), reason:
Objects.cpp 594: exception occurred (Number = 135), reason:
Objects.cpp 241: assertion failed (PatternX = 3) (Entry.PatternWidth = 1), reason:
In(PatternX,1,Entry.PatternWidth)
----------------------------------------------------------------`

**Comment by babymannen** [comment]
Commited fix to this error.
