### ISSUE TITLE
wrong weigh decimals

### ISSUE THREAD

**Issue by Seliro** [babymannen/theforgottenserver-7.4#42]
current:
```
04:51 You see 2 arrows.
They weigh 1.40 oz.
04:52 You see a halberd (Atk:35, Def:14).
It weighs 90.00 oz.
```

should be 1.4 and 90.0 so remove one zero

![asd](http://img.photobucket.com/albums/v482/Hefaxer123/ss_tibia0010.jpg)

**Comment by babymannen** [comment]
Closed to further notice. I made stupid hack because i am noob but if it works it works...

**Comment by Seliro** [comment]
seems like it works
