### ISSUE TITLE
Can't walk through invisible GM

### ISSUE THREAD

**Issue by bangbus** [babymannen/theforgottenserver-7.4#45]
You get `Sorry, not possible.`

Not really high priority but I noticed this testing around.

**Comment by babymannen** [comment]
Commited a potential fix, tested it in different situation, seemed to work. I'll close it til further notice.

**Comment by diegorodriguesvieira** [comment]
Which line of code is? I would like to see how it works :)

**Comment by babymannen** [comment]
I don't understand what you mean, can't you just see it in the commit?

Anyway, it's in Tile::queryAdd(...) function

**Comment by diegorodriguesvieira** [comment]
Sorry man...
