### ISSUE TITLE
Names of other players and npcs are displayed as your own name on screen and in chat

### ISSUE THREAD

**Issue by bangbus** [babymannen/theforgottenserver-7.4#46]
Every name of other players, npcs will be the name of the player you're currently on in chat and on screen, not in battle list though

Look at this and you'll understand, look at the names.

**First players client, the one that wrote it**
![asg](https://cloud.githubusercontent.com/assets/13314890/18030226/f278fda2-6cae-11e6-9c7f-a4ff1449154a.jpg)

**Second players client**
![aass](https://cloud.githubusercontent.com/assets/13314890/18030192/10a69362-6cae-11e6-8ec0-830f662fb2d9.jpg)

**Comment by babymannen** [comment]
fixd
