### ISSUE TITLE
party channel

### ISSUE THREAD

**Issue by Seliro** [babymannen/theforgottenserver-7.4#47]
even tho i left the party, i can still see what the others say in that party channel, i can't type anything so atleast that is correct
```
06:57 Sorcerer two: test
06:57 The channel has been closed. You need to re-join the channel if you get invited.
06:57 Knight: lol he left the party..
06:58 Knight: wierd that he can still see what we type ;s
```

**Comment by dhustkoder** [comment]
doesn't happens when using otclient, the server code isn't wrong in that area, seems like a bug in the custom client within this repo. One way to make everything work is to fork otclient and create a standalone version for this server. Like Medivia/Tibianic does

**Comment by peonso** [comment]
Client here is 7.72 with 7.4 sprites, nothing more is custom. It is bugged.

**Comment by Seliro** [comment]
rather stick with normal client and have it working, not a fan of otclient nor medivia

**Comment by dhustkoder** [comment]
@peonso  the server code requests the client to close the party window when the player leaves the party the custom client here don't do that, while otclient does it. Can you test it with a normal 7.72 client to see if it works ?, then we can digg it cuz might be a protocol problem

**Comment by peonso** [comment]
I'm sure it's a protocol problem, since its normal 7.72 client, only sprites are changed.

**Comment by dhustkoder** [comment]
@peonso  Ok, I found the bug it's simple but happens a lot in messy codebases like OpenTibia codebase. I'll do a pull request
