### ISSUE TITLE
wrong bed appearance

### ISSUE THREAD

**Issue by Seliro** [babymannen/theforgottenserver-7.4#5]
![beds](http://i.imgur.com/YLKo96h.png)

**Comment by babymannen** [comment]
I don't have this problem. Have the bed been used?

**Comment by Seliro** [comment]
yes i used it on the 'Sorcerer' character and logged into GM and inspected the bed

**Comment by Seliro** [comment]
if i go to bed a sorcerer and relog then this happens
![sorc](http://i.imgur.com/1d6F7qB.png)

**Comment by Seliro** [comment]
i just tested on a fresh download, and problem still exists

**Comment by babymannen** [comment]
Pushed a commit, closing. Thanks for reporting this. +1
