### ISSUE TITLE
Can't use ladder if there is any kind of item on it

### ISSUE THREAD

**Issue by bangbus** [babymannen/theforgottenserver-7.4#50]

**Comment by peonso** [comment]
it's an item.otb issue I think, incorrect flag to ladder item, but Seliro told it's intended.

**Comment by Seliro** [comment]
no, it should be an old extra feature, but it is currently enabled is what i meant, however keep in mind that you should be able to rope your loot in the ladders if it is enabled

**Comment by Seliro** [comment]
items on ladder was fixed here https://github.com/babymannen/theforgottenserver-7.4/commit/21e99b57f8f96c39c262740223bc83bf8cca764a, so this can be closed aswell
