### ISSUE TITLE
Does anyone have functioning clients.xml and items.otb/xml for remeres map editor 2.2?

### ISSUE THREAD

**Issue by bangbus** [babymannen/theforgottenserver-7.4#51]
The default 7.4 obviously don't work. Can't get my 7.4 map to work with this distro.

**Comment by peonso** [comment]
Why you not using RME 3.1? What error message you got?

**Comment by bangbus** [comment]
Why not? I get wrong OTB version and with remeres 3.1 i get "This map need to be upgraded with the latest map editor version to be able to load correctly"

**Comment by peonso** [comment]
Try the clients.xml from https://github.com/TwistedScorpio/OTHire/wiki/How-to-use-RME-for-this-OTServer
You can also try to open it with SimOne map editor and resave the map http://www.4shared.com/zip/UrH4nF9Pce/OTMapEditor-04490.html I don't know if this version loads 7.4 though.

**Comment by peonso** [comment]
Also 3.1 will have this https://github.com/hjnilsson/rme/commit/502c29e5c877cc94d16bc7e001c7914254136079 and some other improvements over 2.2

**Comment by bangbus** [comment]
Thanks peonso you're a kind human. I will try that when I'm home!

**Comment by bangbus** [comment]
Also babymannen said he used 2.2 with some special clients.xml and items.otb/xml
He was gonna share it but its been days no word and I can't wait longer

**Comment by bangbus** [comment]
None of your tips worked, even tried saving with RME 3.2. Thanks anyways!

I just get _This_ map need to be upgraded with the latest map editor version to be able to load correctly_

**Comment by babymannen** [comment]
Uploaded the files I use. I know they work, thus closing.
