### ISSUE TITLE
stackpos useitem issue

### ISSUE THREAD

**Issue by Seliro** [babymannen/theforgottenserver-7.4#52]
with the current commit https://github.com/babymannen/theforgottenserver-7.4/commit/21e99b57f8f96c39c262740223bc83bf8cca764a

https://github.com/babymannen/theforgottenserver-7.4/blob/21e99b57f8f96c39c262740223bc83bf8cca764a/src/game.cpp#L246

it fixed so you can click on ladders regardless of item or field on the stack

the problem that appeared instead is that now you cannot use items that is on the ground, example runes, sewers, fishing rod etc.

**Comment by Seliro** [comment]
seems like it was missing
`thing = tile->getUseItem();`

under this line
https://github.com/babymannen/theforgottenserver-7.4/blob/21e99b57f8f96c39c262740223bc83bf8cca764a/src/game.cpp#L246

if this is correct way to fix it, then commit it

**Comment by Seliro** [comment]
corpses cannot be looted on the ground tho

**Comment by babymannen** [comment]
Reverted change for now

**Comment by babymannen** [comment]
Posted new fix, please test it. I only tested it briefly

**Comment by Seliro** [comment]
corpse issue still exist tho

**Comment by babymannen** [comment]
Changed back once again

**Comment by babymannen** [comment]
Seems to work now, closing
