### ISSUE TITLE
gate of expertise

### ISSUE THREAD

**Issue by Seliro** [babymannen/theforgottenserver-7.4#54]
`add level and only the worthy may pass`
![img](https://camo.githubusercontent.com/5b234d19070bdbb54ce7ee87056d23785627c1b6/687474703a2f2f696d672e70686f746f6275636b65742e636f6d2f616c62756d732f763633382f4368616c6b612f33356c766c676174652e6a7067)

**Comment by peonso** [comment]
How is it currently??

**Comment by Seliro** [comment]
08:39 You see a gate of expertise.

**Comment by babymannen** [comment]
It shows what level it is for me. Added "only worthy may pass" though. Closing
