### ISSUE TITLE
monster loot issue

### ISSUE THREAD

**Issue by Seliro** [babymannen/theforgottenserver-7.4#56]
they currently don't drop loot inside their bags

**Comment by babymannen** [comment]
They do for me. You need to update your local repo

**Comment by peonso** [comment]
https://github.com/babymannen/theforgottenserver-7.4/commit/0e746a515e910d6cca81d2f80ba9057e4b5ff1b8

You need to remove the `<inside></inside>` tags, they fuck it up.

**Comment by babymannen** [comment]
Fixed, closed
