### ISSUE TITLE
first login

### ISSUE THREAD

**Issue by Seliro** [babymannen/theforgottenserver-7.4#57]
if you create a female character for the first time and you login, it has the male outfit until you change it currently

**Comment by peonso** [comment]
Create a character through what? It probably an AAC error, that is not setting the female outfit correctly.

**Comment by Seliro** [comment]
added it myself to player table with sex = 0, you can pick female outfits tho but the character is male until change

**Comment by peonso** [comment]
And the starting outfit? 128??

**Comment by Seliro** [comment]
oh lololol :+1:
