### ISSUE TITLE
heal issue

### ISSUE THREAD

**Issue by Seliro** [babymannen/theforgottenserver-7.4#59]
you currentl'y cannot heal yourself, tested with exura vita / ultimate healing rune

might be something missing here
https://github.com/babymannen/theforgottenserver-7.4/commit/a57ecf8e453c847e56a89b6708a870f70152d06b
https://github.com/babymannen/theforgottenserver-7.4/commit/b6ac2401890ba5f3a3c82d3f8975b341bb6d0d11

**Comment by babymannen** [comment]
Fixd
