### ISSUE TITLE
speed issue

### ISSUE THREAD

**Issue by Seliro** [babymannen/theforgottenserver-7.4#6]
if you run as god or as a high level character for this example lvl 450, you will notice a wierd lagg of some sort (not internet connection nor fps). it is slowing you down anywy.

maby someone can test it aswell, coz i have not had this issue on any other distro before

**Comment by babymannen** [comment]
Happens only on GM character? Since their speed is 1500 (a.k.a. PLAYER_MAX_SPEED) in OTServ tier servers the baseSpeed for GMs is 900. I don't lagg
