### ISSUE TITLE
npc queue system

### ISSUE THREAD

**Issue by Seliro** [babymannen/theforgottenserver-7.4#64]
there is currently no queue system for npcs

```
10:34 Seliro: hi
10:34 Eryn: Hello Seliro. I sell runes, potions, wands and rods.
10:34 Sorcerer: hi
10:34 Eryn: Hello Sorcerer. I sell runes, potions, wands and rods.
```

could use something like this aswell
npcHandler:setMessage(MESSAGE_BUSY, "im busy talking to someone else")

**Comment by babymannen** [comment]
Commited a fix. Only tested it like this:

FirstPlayer: Hello
Npc: Hello
SecondPlayer: Hello
Npc: Wait for your turn

More testing is needed

**Comment by Seliro** [comment]
```
00:08 Sorcerer: hi
00:08 Eryn: Hello Sorcerer. I sell runes, potions, wands and rods.
00:08 Seliro: hi
00:08 Eryn: Seliro, please wait for your turn. There are 1 customers before you.
00:09 Paladin Damage: hi
00:09 Eryn: Paladin Damage, please wait for your turn. There are 2 customers before you.
00:11 Eryn: Hello Seliro. I sell runes, potions, wands and rods.
00:11 Eryn: Hello Paladin Damage. I sell runes, potions, wands and rods.
00:11 Eryn: Good bye, Paladin Damage.
```
when it's 'seliro's turn the npc skips both 'seliro' and 'paladin damage' and goes directly into idle mode instead

**Comment by babymannen** [comment]
Should be fixed now. If you wonder why I don't tab, I can't tell you why. I have reset my editors settings to default, let's hope that works...
