### ISSUE TITLE
(minor issues) redo some message tags

### ISSUE THREAD

**Issue by Seliro** [babymannen/theforgottenserver-7.4#66]
npc missing items message
--------------
**[MESSAGE_MISSINGITEM]**
https://github.com/babymannen/theforgottenserver-7.4/blob/master/server/data/npc/lib/npcsystem/npchandler.lua#L90

for more than one missing item, add this
 **[MESSAGE_MISSINGITEMS]**

no plural thing here since the message could be completely different from the other

npc decline message issue
--------------
**[MESSAGE_DECLINE]**
https://github.com/babymannen/theforgottenserver-7.4/blob/master/server/data/npc/lib/npcsystem/npchandler.lua#L96

have two seperate decline messages instead
**[MESSAGE_BUY_DECLINE], [MESSAGE_SELL_DECLINE]**

**Comment by peonso** [comment]
For first issue: https://github.com/babymannen/theforgottenserver-7.4/blob/5e084e8743b309246779d8807b261cc0d3ae41fc/server/data/actions/scripts/quests/system.lua#L62
If you only add an S you fuck up irregular plurals.

**Comment by Seliro** [comment]
ok this seems to work

```
if count > 1 then
	shop_rlname[cid] = parameters.realName .. ItemType(itemid):getPluralName()
else
	shop_rlname[cid] = parameters.realName
end
```

**Comment by babymannen** [comment]
I would suggest that in the shop system, we simply use what the NPC should say (will be easier for those who want more modification to their NPCs) 

Example:
shopModule:addBuyableItem({'boh'}, 2195, 100, |ITEMCOUNT| > 0 and "Do you want to buy 2 boh?" or "Do you, mister custom message, want to buy a PAIR of boh?")

**Comment by peonso** [comment]
@Seliro just trying to mimic what should be default server behavior. It's a Lua interface, if people want to use custom stuff they should do that themselves, not that you can't easy it, just don't think it should be focus. https://github.com/TwistedScorpio/OTHire/issues/80

**Comment by Seliro** [comment]
|TIME| also got lost btw

**Comment by babymannen** [comment]
Re-added time again. Closing.
