### ISSUE TITLE
(minor issue) msgcontains don't allow dashes

### ISSUE THREAD

**Issue by Seliro** [babymannen/theforgottenserver-7.4#67]
https://github.com/babymannen/theforgottenserver-7.4/blob/918264c514d4def5b59204021ddc9bde9e7e7498/server/data/npc/lib/npc.lua#L04

`msgcontains(msg, "test-lol")`

issue:  it does not allow dashes currently

**Comment by peonso** [comment]
It a lua issue, try `msgcontains(msg, "test%-lol")`

**Comment by Seliro** [comment]
ok, ye it works
