### ISSUE TITLE
(crash) walk into doors

### ISSUE THREAD

**Issue by Seliro** [babymannen/theforgottenserver-7.4#69]
server crashing if walk through the gate of expertise south of test temple
tested on 38 sorcerer and GM, both crashes it
```
01:24 You see a gate of expertise for level 10.
Only the worthy may pass.
Item ID: 1229, Action ID: 1010
Position: 997, 1011, 7
```

```
<item id="1229" article="a" name="gate of expertise">
		<attribute key="type" value="door" />
		<attribute key="leveldoor" value="1000" />
		<attribute key="blockprojectile" value="1" />
        <attribute key="description" value="Only the worthy may pass." />
</item>
```

**Comment by peonso** [comment]
It crashes when you click on it, or when you leave it?

**Comment by Seliro** [comment]
it's not just gate of expertise btw, the other doors aswell (not houses it seems like), from what i tested

**Comment by peonso** [comment]
Tried to kick/logout the character instead of moving, still crashes.

**Comment by Seliro** [comment]
hmm door id: 1221 too

**Comment by peonso** [comment]
It was https://github.com/babymannen/theforgottenserver-7.4/commit/242e47e208279ed4205a48b3bdeed3d1193d08f6, tryed with previous state _exe_ and no crash.

**Comment by Seliro** [comment]
also if you try to equip an item from distance it crashes

**Comment by babymannen** [comment]
Make new issue about equip think blz

**Comment by Seliro** [comment]
did

**Comment by dhustkoder** [comment]
This problem is about a nullptr dereference in tile.cpp 540, 
you guys need to add this check for the creatures pointer after the foreach loop

**Comment by babymannen** [comment]
Fixed by dhustkoder
