### ISSUE TITLE
Monsters take to much time to change pathing

### ISSUE THREAD

**Issue by peonso** [babymannen/theforgottenserver-7.4#7]
https://otland.net/threads/weird-monster-behaviour-in-tfs-1-1.228021/#post-2200365

https://github.com/babymannen/theforgottenserver-7.4/blob/master/src/creature.cpp#L625

**Comment by Seliro** [comment]
i dont yet understand github so much but i did something like this based on that thread

`if (!g_config.getBoolean(ConfigManager::MONSTER_PATH_SPEED)) {
				isUpdatingPath = true;
			}
			else {
				isUpdatingPath = false;
				g_dispatcher.addTask(createTask(std::bind(&Game::updateCreatureWalk, &g_game, getID())));
			}`

**Comment by babymannen** [comment]
It's already in the source code.
