### ISSUE TITLE
distance weapons

### ISSUE THREAD

**Issue by Seliro** [babymannen/theforgottenserver-7.4#74]
currently displaying (range: x), if i remember correct it should be removed
```
11:25 You see a crossbow (Range:5).
It weighs 40.0 oz.
```

```
11:25 You see a bow (Range:6).
It weighs 31.0 oz.
```

for other distance weapons im not sure if they should display (atk:x) or not, but i dont think so
```
11:27 You see a spear (Atk:25).
It weighs 20.0 oz.
```

**Comment by babymannen** [comment]
Fixed
