### ISSUE TITLE
save items on the map when serversave

### ISSUE THREAD

**Issue by Seliro** [babymannen/theforgottenserver-7.4#76]
https://youtu.be/a9FbrBmOseI?t=1m50s

if this is set to false i guess
https://github.com/babymannen/theforgottenserver-7.4/blob/master/server/data/globalevents/scripts/serversave.lua#L02

**Comment by babymannen** [comment]
Did you test this or what?

**Comment by Seliro** [comment]
i tested it and it doesn't work no, dont think it's coded

**Comment by babymannen** [comment]
This is not a standard feature in OT, which mean I won't waste time on fixing it. Sorry.

**Comment by peonso** [comment]
If you read the code you will se that the server can either shutdown, or just be closed, if it's closed it check if you want to clean the map or not. If you set both to false it will save and not clean the map. Hence once you shutdown the clean is forced.

**Comment by Seliro** [comment]
yeah i knw about that, not what i was after tho
