### ISSUE TITLE
light doesn't work from equipped item 

### ISSUE THREAD

**Issue by Seliro** [babymannen/theforgottenserver-7.4#77]
say you got a fire axe equipped and in .dat it has a color with light density

currently it works if you just have it on the ground, but when you equip it, it doesn't.

it works on latest TFS btw just tested

**Comment by babymannen** [comment]
It works for me.

**Comment by babymannen** [comment]
https://i.gyazo.com/a5ee5b23d15fbcabf459e2a6e3661830.png
https://i.gyazo.com/1e94e005f0c58df9b6a733e1b971df51.png

**Comment by Seliro** [comment]
you gotta change the lightcolor first

**Comment by babymannen** [comment]
IIRC there are no different colors in 7.4. I beleive that came in 7.6.

**Comment by Seliro** [comment]
yep i knw, still not correct in source tho. even if you want the light to be 215 as it was in 7.4
