### ISSUE TITLE
autostack items

### ISSUE THREAD

**Issue by Seliro** [babymannen/theforgottenserver-7.4#78]
here is the previous code i did and yeah with config option
https://github.com/oldtibia/theforgottenserver-7.4/commit/faa18ae10f3c79a1644c746a791915f23bbd10e2

just close if you dont want it

it is enabled currently without it

**Comment by babymannen** [comment]
How is this an issue?

**Comment by Seliro** [comment]
well it's not 7.4, so yeah it is an issue
autostacking didn't even exist, however i added it as a config option
