### ISSUE TITLE
party info when looking a player

### ISSUE THREAD

**Issue by peonso** [babymannen/theforgottenserver-7.4#8]
https://github.com/babymannen/theforgottenserver-7.4/blob/master/src/player.cpp#L223

	/* 
	// Removing Party and Guild information from LOOK message.
	if (party) {
		if (lookDistance == -1) {
			s << " Your party has ";
		} else if (sex == PLAYERSEX_FEMALE) {
			s << " She is in a party with ";
		} else {
			s << " He is in a party with ";
		}

		size_t memberCount = party->getMemberCount() + 1;
		if (memberCount == 1) {
			s << "1 member and ";
		} else {
			s << memberCount << " members and ";
		}

		size_t invitationCount = party->getInvitationCount();
		if (invitationCount == 1) {
			s << "1 pending invitation.";
		} else {
			s << invitationCount << " pending invitations.";
		}
	}
	*/
	if (guild) {
		const GuildRank* rank = guild->getRankByLevel(guildLevel);
		if (rank) {
			if (lookDistance == -1) {
				s << " You are ";
			} else if (sex == PLAYERSEX_FEMALE) {
				s << " She is ";
			} else {
				s << " He is ";
			}

			s << rank->name << " of the " << guild->getName();
			if (!guildNick.empty()) {
				s << " (" << guildNick << ')';
			}
			// Adding period in the end of the message (part of the Removing Party and Guild information from LOOK message change)
			s << ".";
			/*
			// Removing Party and Guild information from LOOK message.
			size_t memberCount = guild->getMemberCount();
			if (memberCount == 1) {
				s << ", which has 1 member, " << guild->getMembersOnline().size() << " of them online.";
			} else {
				s << ", which has " << memberCount << " members, " << guild->getMembersOnline().size() << " of them online.";
			}
			*/
		}
	}

**Comment by babymannen** [comment]
Fixed. Thanks.
