### ISSUE TITLE
destroy fields

### ISSUE THREAD

**Issue by Seliro** [babymannen/theforgottenserver-7.4#87]
this is how it currently is
![img](http://i.imgur.com/Nq6bwWf.png)

this is how it should be
https://youtu.be/6afMp0WJ-hk?t=17m

**Comment by dhustkoder** [comment]
where can I get the map and the scripts to test it ?

**Comment by Seliro** [comment]
the scripts is from this repo. you have the item ids on the screenshot just create them and test with the map that follows?

https://github.com/babymannen/theforgottenserver-7.4/blob/master/server/data/spells/scripts/support/destroy%20field%20rune.lua

if you need realmap there are distros that includes it for example othire, otx etc

**Comment by peonso** [comment]
Can you check if destroy field is removing magic wall/wild growth?

**Comment by Seliro** [comment]
@peonso it doesn't

**Comment by peonso** [comment]
@dhustkoder added to test map, update repository, below depot.

**Comment by dhustkoder** [comment]
@peonso nice

**Comment by Seliro** [comment]
below temple * : )

**Comment by dhustkoder** [comment]
do you know the key's id ? I can destroy the energy fields correctly, I'm trying to reproduce that problem

**Comment by peonso** [comment]
2092

**Comment by dhustkoder** [comment]
strange, I destroyed the energy fields normaly with the key below it , just can't destroy those who had ashes below them and the smoke, should it be destroyed ?

**Comment by Seliro** [comment]
stack order
```
fire field
energy field
key
```

use destroy field = all fields on the stack gets destroyed

**Comment by dhustkoder** [comment]
@Seliro  thanks, I'm looking into it

**Comment by dhustkoder** [comment]
@Seliro  solved it

**Comment by Seliro** [comment]
it fixes picture 3 problem
however, need to fix so it removes all fields in the stack

**Comment by dhustkoder** [comment]
Oh so The rune should destroy ali fields? If is that it Ill check in a minute

**Comment by dhustkoder** [comment]
@Seliro  should it use 1 charge regardless of how many fields it removes ?

**Comment by Seliro** [comment]
ye all, and about the charges i have no idea, but i think so

**Comment by peonso** [comment]
Just one charge, for sure.

**Comment by dhustkoder** [comment]
just fixed the script, I've squashed it into my pull request take a look

**Comment by dhustkoder** [comment]
it is removing those searing fields now, I'll check it out

**Comment by dhustkoder** [comment]
Ok now seems to be allright, I've squashed it

**Comment by Seliro** [comment]
yeah seems like it works, good job

**Comment by peonso** [comment]
I can't compile it right now, can you guys check if you throw field bomb above it fields are replaced?

**Comment by dhustkoder** [comment]
Ill be optimizing that changes in half hour or so then I can test it out
@peonso

**Comment by dhustkoder** [comment]
@peonso I used adevo mas flam rune into the fire field/energy fields and it wasn't replaced by the fire is it the right behaviour ?

**Comment by peonso** [comment]
No, the new field should replace all fields in the tile.

**Comment by dhustkoder** [comment]
@peonso  So, if i got that right, the new field should remove all the fields that were there and then stay there alone ? if so, the problem may be on the script that throws the rune

**Comment by peonso** [comment]
Yeah, you got it right. I'm not sure where the problem lies, but I think it's here https://github.com/babymannen/theforgottenserver-7.4/blob/master/src/tile.cpp#L886

**Comment by dhustkoder** [comment]
@peonso  nice, I'll debug it later, I'm trying to optimize the recent changes that fixed this issue to a more reasonable solution, maybe you should push a new issue for that and we can solve it there, since this issue is already closed
