### ISSUE TITLE
Field runes does not replace other fields

### ISSUE THREAD

**Issue by peonso** [babymannen/theforgottenserver-7.4#88]
New field should replace all fields in the tile.

I'm not sure where the problem lies, but I think it's here https://github.com/babymannen/theforgottenserver-7.4/blob/master/src/tile.cpp#L886

https://github.com/babymannen/theforgottenserver-7.4/issues/87#issuecomment-249298750

**Comment by Seliro** [comment]
just tested with 
https://github.com/babymannen/theforgottenserver-7.4/commit/4c255a16c69b2e935ada556bd1f821de128d36e0

and bug still exist

**Comment by dhustkoder** [comment]
@peonso seems that the fields are configured to not be replaceable, shouldn't it be set to 1 ?
https://github.com/babymannen/theforgottenserver-7.4/blob/master/server/data/items/items.xml#L716

**Comment by dhustkoder** [comment]
just set it to 1 on all fields that should be replaced and this issue is gone

**Comment by peonso** [comment]
It removes both fields in those draconia key thing? You can just remove the line instead of setting it to 1, its default.

**Comment by dhustkoder** [comment]
is there any field that should not be replaceable ? if so list it here, I'll test it now, and I'm improving the code on Tile::addThing as a bonus

**Comment by peonso** [comment]
https://github.com/babymannen/theforgottenserver-7.4/blob/master/server/data/items/items.xml#L667-L755 These should be replaceable.

**Comment by Seliro** [comment]
i think ladder/rope field bug is back, @peonso can you confirm?

**Comment by dhustkoder** [comment]
yeah it removes both fields, just needed to correct the loop, taking out the break

**Comment by dhustkoder** [comment]
@peonso  pull request ready for review/test

**Comment by peonso** [comment]
@Seliro I can't confirm, I didn't get a compiler set up here. What exactly bug are you referring to?

**Comment by Seliro** [comment]
@peonso nvm, it's either my 7.72 .otb or .dat causing ladders not to be clickable if item/field on it
